
class ErrorMessageConst{
  static const String  SERVER_FAILURE_MESSAGE="SERVER_FAILURE_MESSAGE";
  static const String  CACHED_FAILURE_MESSAGE="CACHED_FAILURE_MESSAGE";
  static const String  INVALED_INPUT_FAILURE_MESSAGE="INVALED_INPUT_FAILURE_MESSAGE";
}